language: java

# Taken from https://docs.travis-ci.com/user/languages/java/

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8

git:
  depth: 1

script:
  - mvn test -B
